<?php

/**
 * @file
 * ldnddev Blockquote module file.
 */

/**
 * Implements hook_theme().
 */
function ldnddev_blockquote_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ldnddev_blockquote' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_blockquote_item' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_blockquote' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_blockquote_item' => [
      'base hook' => 'paragraph',
    ],
  ];
}
